language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angular-grails-simple' ]; then cd .. && eval "mv $currentfolder generator-angular-grails-simple" && cd generator-angular-grails-simple; fi

